apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2021-11-27T19:47:29Z"
  generation: 1
  labels:
    app: currency-conversion-service
  name: currency-conversion-service
  namespace: default
  resourceVersion: "146772"
  uid: f9544444-0333-4ccd-9506-de1af6f5fb89
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-conversion-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-conversion-service
    spec:
      containers:
      - image: sreemarshal/micro-sp-test-currency-conversion-service:0.0.12-SNAPSHOT
        env:
         - name: CURRENCY_EXCHANGE_MY
           value: http://currency-exchange
        imagePullPolicy: IfNotPresent
        name: micro-sp-test-currency-exchange      
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-11-27T19:47:38Z"
    lastUpdateTime: "2021-11-27T19:47:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-11-27T19:47:29Z"
    lastUpdateTime: "2021-11-27T19:47:38Z"
    message: ReplicaSet "currency-conversion-service-6f9b6b5df4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-11-27T19:48:54Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: currency-conversion-service
  name: currency-conversion-service
  namespace: default
  resourceVersion: "147502"
  uid: 0927d23a-c54a-47b3-9a92-04bdc62802ec
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30698
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: currency-conversion-service
  sessionAffinity: None
  type: LoadBalancer
