---
services:
  currency-exchange:
    image: "sreemarshal/micro-sp-test-currency-exchange:0.0.1-SNAPSHOT"
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - limit-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE : http://limit-service:8761/eureka
      SPRING.ZIPKIN.BASEURL : http://zipkin-server:9411/

  limit-service:
    image: "sreemarshal/micro-sp-test-limit-service:0.0.1-SNAPSHOT"
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: "openzipkin/zipkin:2.23"
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network

  rabbitmq:
    image: "library/rabbitmq:3.5.3-management"
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network


networks:
  currency-network:
